import os
import re
import h5py
import numpy as np
from tqdm import tqdm
import pickle
from os.path import join

"""
This file oriented to work with output from PIConGPU library
https://github.com/ComputationalRadiationPhysics/picongpu
"""

__all__ = ['get_grid_steps', 'read_positions', 'density_from_fields', 'read_probe_field', 'read_field',\
'proj', 'load_line', 'probes2h5', 'find_params']

def get_grid_steps(m, multiplier = 1):
	"""
	Reads spatial grid steps from h5py.AttributeManager

	Parameters
	----------
	m - AttributeManager
	mutliplier - conversion from m to another unit (default - to um)

	Returns
	----------
	grid steps
	"""
	ul = m['unit_length']
	dx, dy, dz = [m[attr] * ul * multiplier for attr in ['cell_width', 'cell_height', 'cell_depth']]
	return dx, dy, dz


def read_positions(f, species, two_dim = True):		
	"""
	reads positions of particles of species from picongpu hdf5 file

	Parameters
	----------
	f - h5py file object
	species - title of species
	two-dim - if calculation was two dimensional

	Returns
	----------
	arrays of particle positions
	"""
	x = np.array(f['particles'][species]['position']['x'])
	Dx = np.array(f['particles'][species]['positionOffset']['x'])

	y = np.array(f['particles'][species]['position']['y'])
	Dy = np.array(f['particles'][species]['positionOffset']['y'])

	if not two_dim:
		z = np.array(f['particles'][species]['position']['z'])
		Dz=np.array(f['data'][str(time_step)]['particles'][species]['positionOffset']['z'])
	
		return (x + Dx), (y + Dy), (z + Dz)
	else:
		return (x + Dx), (y + Dy)


def density_from_fields(f, species = 'e', uc = -1.6e-19, dataset = 'fields'):

	"""
	reads species density if it was written in fields dataset

	Parameters
	----------
	f - h5py file object
	species - title of species
	uc - unit charge of species

	Returns
	----------
	density in 1 / m^3 (SI units)
	"""
	dens = np.array(f[dataset][species + '_all_chargeDensity'])
	unit_si_dens = h5py.AttributeManager(f[dataset][species + '_all_chargeDensity'])['unitSI']
	if dataset == 'fields':
		unit_si_dens /= uc
	return dens * unit_si_dens 


def read_probe_field(f, field, axis, ii, jj, kk = None, species = 'p'):
	"""
	retrieves field map from probe particles

	Parameters
	----------
	f - h5py file object
	field - field to plot(E or B)
	axis - component of field to read (0 - x, 1 - y, 2 - z)
	ii, jj, kk - positions for probe particles
	species - name of probe particles

	Returns
	----------
	field in SI units (E/m for electric or Tl for magnetic)
	"""
	F_flat = np.array(f['particles'][species]['probe' + field][axis])
	F_unit_si = h5py.AttributeManager(f['particles'][species]['probe' + field][axis])['unitSI']

	two_dim = (kk is None)

	nx = len(np.unique(ii))
	ny = len(np.unique(jj))
	if two_dim:
		shape = (nx, ny)
	else:
		nz = len(np.unique(kk))
		shape = (nx, ny, nz)

	
	if two_dim:
		idx = ii * ny + jj
		F = np.zeros_like(F_flat)
		F[idx] = F_flat
		F = F.reshape(shape)

	else:
		F = np.zeros(shape, dtype = 'float32')
		for i in range(len(F_flat)):
			F[ii[i], jj[i], kk[i]] = F_flat[i]
	return F * F_unit_si


def read_field(f, field, axis, dataset = 'fields'):
	"""
	reads field from picongpu hdf5 file

	Parameters
	----------
	f - h5py file object
	field - field to plot (E, B or charge density)
	axis - component of field to read (0 - x, 1 - y, 2 - z)

	Returns
	----------
	field in SI units
	"""
	F_unit_si = h5py.AttributeManager(f[dataset][field][axis])['unitSI']
	F = f[dataset][field][axis]
	return	 F_unit_si * F


def proj(s, n):
	return float(s[1:-1].split(',')[n])

projv = np.vectorize(proj)

def load_line(filename, axes, dtype = 'float32'):
	"""
	reads one file generated by PIConGPU slice printer plugin

	Parameters
	----------
	filename - path to file, where one slice was dumped by slice printer plugin
	axes - axes of field vector to load (x-0, y-1, z-2)
	dtype - dtype to load data in

	Returns
	----------
	values from line
	----------
	"""
	with open(filename, 'r') as f:
		line = next(iter(f))
		line = line.split(' ')[:-1]
		line = [projv(np.array(line) , axis).astype(dtype) for axis in axes]
		return line


def probes2h5(path, dest_path, format_str = "simData_p_\d+.h5", fn2ts = lambda x:int(x.split('_')[-1][:-3]),\
 idx_min = 0, idx_max = -1, verbose = True, axes_E = ['x', 'y', 'z'], axes_B = ['x', 'y', 'z'], dtype = '<f4',\
 species = 'p'):
	"""
	converts directory with probes data to single h5 file with attributes ('dx_SI, dt_SI (period of probes recording)')
	"""
	valid_format = re.compile(format_str)
	files = list(filter(valid_format.match, os.listdir(path)))

	files = sorted(files, key = fn2ts)[idx_min: idx_max]
	
	d_idx = fn2ts(files[1]) - fn2ts(files[0])
	
	E, B = None, None
	
	for i, file in tqdm(enumerate(files), total = len(files)) if verbose else enumerate(files):
		with h5py.File(join(path, file), 'r') as f:
			m = h5py.AttributeManager(f['data'][str(fn2ts(file))])
			f = f['data'][str(fn2ts(file))]['particles'][species]
			ids = np.array(f['id'])

			x = np.array(f['positionOffset']['x'], dtype = 'uint16')
			y = np.array(f['positionOffset']['y'], dtype = 'uint16')  

			idx = np.argsort(ids)

			xy = np.vstack((x[idx], y[idx])).T


			if i == 0:
				ids0 = ids.copy()
 
				E = np.zeros((len(files), len(idx), len(axes_E)), dtype = dtype)
				B = np.zeros((len(files), len(idx), len(axes_B)), dtype = dtype)			 
				
				dt_SI = m['unit_time']
				dx_SI = m['unit_length'] * m['cell_width']
				
				m = h5py.AttributeManager(f['probeE']['x'])
				E_SI = m['unitSI']
				m = h5py.AttributeManager(f['probeB']['x'])
				B_SI = m['unitSI']

			E_ds, B_ds = np.array([np.array(f['probeE'][axis]) for axis in axes_E]),\
						 np.array([np.array(f['probeB'][axis]) for axis in axes_B])


			E[i] = E_ds.T[idx]
			B[i] = B_ds.T[idx]
	
	# with open(r"C:\Users\lenovo\OneDrive\Рабочий стол\2\PIC\D_6.67_H_1.45_AOI_25_L_5\save.pkl", 'rb') as f:
	# 	d = pickle.load(f, encoding = 'latin1')

	# E = d['E']
	# B = d['B']
	# xy = d['xy']
	# dx_SI = d['dx_SI']
	# dt_SI = d['dt_SI'] * 15


	with h5py.File(dest_path, 'w') as f:
		grp = f.create_group('data')
		grp.attrs['dx_SI'] = dx_SI
		grp.attrs['dt_SI'] = dt_SI * d_idx
		E_grp = grp.create_group('E')
		B_grp = grp.create_group('B')
		for i, axis in enumerate(axes_E):
			E_grp.create_dataset(axis, data = E[:, :, i])
		for i, axis in enumerate(axes_B):
			B_grp.create_dataset(axis, data = B[:, :, i])
		grp.create_dataset('xy', data = xy)



	# return {'E' : E * E_SI, 'B' : B * B_SI, 'xy' : xy, 'dt_SI' : dt_SI, 'dx_SI' : dx_SI}


def find_params(path, file, params):
	"""
	Scans specified directory and specified picongpu .param or .cfg file to find simulation params.
	if param expressed through laser wavelenght, it is evaluated in SI units
	"""
	with open(join(path, 'picongpu', 'param', '{}.param'.format(file)), 'r') as f:
		content = f.read()
		vals = {}
		for p in params:
			match_str = f'{p} = .+;'
			res = re.search(match_str, content)
			val_str = content[res.start() + len(rf'{p} = '):res.end() - 1]
			try:
				vals[p] = float(val_str)
			except ValueError:
				if 'wavelength' in val_str:
					wavelength = find_params(path, 'grid', ['wavelength'])['wavelength']
					vals_str = val_str.replace('SI::wavelength', f'{wavelength}').replace('wavelength', f'{wavelength}')
					vals[p] = eval(vals_str)
				else:
					vals[p] = val_str

	return vals


def load_xt_map(path, axes, step = 2, dtype = 'float32'):
	"""
	loads xt map from directory, where PIConGPU slice printer plugin dumped data

	Parameters
	----------
	path - path to directory, whrer slice printer dumped results
	axes -  axes of field vector to load (x-0, y-1, z-2)
	step - step to iterate through file list
	dtype - dtype to load data

	Returns
	----------
	xt-map(s), recorded in directory
	"""
	if type(axes) == int:
		axes = [axes]
	files = sorted(os.listdir(path), key = lambda s : int(s[6:-4]))
	files = files[::step]
	lines0 = load_line(join(path, files[0]), axes, dtype = dtype)
	Ny, Nt = len(lines0[0]), len(files)
	F = [np.zeros((Nt, Ny), dtype = dtype) for _ in axes]
	for i in range(len(axes)):
		F[i][0, :] = lines0[i]
	for j, file in tqdm(enumerate(files[1:])):
		lines0 = load_line(join(path, file), axes = axes, dtype = dtype)
		for i in range(len(axes)):
			F[i][j, :] = lines0[i]
	return F