import os
import h5py
import copy
import numpy as np
from collections.abc import Iterable
from scipy.signal import windows
from scipy.interpolate import RegularGridInterpolator
from mpl_toolkits.axes_grid1 import make_axes_locatable

# from .plot_utils import _get_ticks, _round
from .math_utils import fft2_filter_F, F2
from .base_map import base_map, inplacify
from .file_utils import (
	get_grid_steps,
 	read_field,
	read_positions, 
	read_probe_field,
	density_from_fields
	)

from .constants import *

import matplotlib
matplotlib.use(mpl_backend)
import matplotlib.pyplot as plt
from collections.abc import Iterable

__all__ = [
	'spectral_window2D',
	'SG_filter2D',
	'xy_map'
]


def spectral_window2D(window_base_fn, shape):
	return window_base_fn(shape[0]).reshape(-1, 1) * window_base_fn(shape[1]).reshape(1, -1)


def SG_filter2D(shape, dx, dy, Rmax, order = 6, is_Fourier_space = True, as_xymap = False):
	if is_Fourier_space:
		size_x, size_y = 2 * np.pi / dx, 2 * np.pi / dy
	else:
		size_x, size_y =  shape[1] * dx, shape[0] * dy
	x = np.linspace(-0.5, 0.5, shape[1]) * size_x
	y = np.linspace(-0.5, 0.5, shape[0]) * size_y
	X, Y = np.meshgrid(x, y)
	R_sqr = X * X + Y * Y
	Filter = np.exp(-(R_sqr / (Rmax * Rmax)) ** (0.5 * order))
	if as_xymap:
		return xy_map(Filter, x[1] - x[0], y[1] - y[0], x_origin = x[0], y_origin = y[0])
	else:
		return Filter

class xy_map(base_map):
	"""
	class to process & analyze spatial distributio of field and species density
	"""
	def __init__(self, A, dx = 1, dy = 1, x_origin = 0, y_origin = 0,\
	 x_title = 'x, cell', y_title = 'y, cell'):
		super().__init__(A, dx, dy, x_origin = x_origin, y_origin = y_origin,\
		x_title = x_title, y_title = y_title)


	@staticmethod
	def from_openPMD(directory, time_step, field, from_probes = False,\
	 dataset_name = 'fields', filename = 'simData_', species = 'p'):
		"""
		reads data from openPMD file, generated by picongpu simulation
		"""
		assert not(('n' in field) and (from_probes)), 'cannot read density from probes'


		f = h5py.File(os.path.join(directory, f"{filename}{time_step:06d}.h5"))
		f = f['data'][f'{time_step}']
		m = h5py.AttributeManager(f)
		dx, dy, _ = get_grid_steps(m, multiplier = 1e6)


		if from_probes:
			yp, xp = read_positions(f, species)
			tmp_x, tmp_y = list(set(xp)), list(set(yp))
			tmp_x, tmp_y = np.partition(tmp_x, 2)[:2], np.partition(tmp_y, 2)[:2]
			sx, sy = int(tmp_x[1] - tmp_x[0]), int(tmp_y[1] - tmp_y[0])

			x_origin = np.min(yp) * dy 
			y_origin = np.min(xp) * dx

			dx, dy = sx * dx, sy * dy
			A = read_probe_field(f, field[0], field[1],\
	 			(xp - np.min(xp)).astype('int32') // sx, (yp - np.min(yp)).astype('int32') // sy, species = species)

		else:
			A = read_field(f, field[0], field[1], dataset = dataset_name)\
			 if not 'n' in field else density_from_fields(f, field[1], dataset = dataset_name)
			x_origin, y_origin = 0, 0#A.shape[1] // 2 * dx,  A.shape[0] // 2 * dx,

		# x_origin, y_origin = 0,0 
		return xy_map(A, dx, dy, x_title = 'x, $\mu m$', y_title = 'y, $\mu m$',\
		 x_origin = x_origin, y_origin = y_origin)

	@staticmethod
	def from_openPMD_api(path, field, from_probes = False):
		if from_probes:
			pass
		else:
			pass

	@inplacify
	def compute_spectrum2D(self):
		"""
		computes 2D FFT to get spectrum
		"""
		A_hat = F2(self.data)
		print(self.dx)
		new_dx, new_dy = 1 / (self.data.shape[1] * self.dx), 1 / (self.data.shape[0] * self.dy)

		self.x_title = super()._fft_switch_axis(self.x_title)
		self.y_title = super()._fft_switch_axis(self.y_title)
		
		self.data = A_hat
		self.dx, self.dy = new_dx, new_dy
		self.x_origin = -.5 * self.data.shape[1] * new_dx
		self.y_origin = -.5 * self.data.shape[0] * new_dy
		return self
 

	@inplacify
	def to_polar_interp(self):
		"""
		transforms data from cartesian units to polar
		"""
		Ny, Nx = self.data.shape
		
		borders_x = -.5 * Nx * self.dx, .5 * Nx * self.dx
		borders_y = -.5 * Ny * self.dy, .5 * Ny * self.dy
		
		x, y = np.linspace(*borders_x, Nx), np.linspace(*borders_y, Ny)
		
		interp = RegularGridInterpolator((y, x), self.data, bounds_error = False, fill_value = 0)
		kr, theta = np.linspace(0, np.sqrt(x[-1] ** 2 + y[-1] ** 2), len(x)),\
				np.linspace(0, 2 * np.pi, len(y)) 

		kr, theta = np.meshgrid(kr, theta)
		Kx, Ky = kr * np.sin(theta), kr * np.cos(theta)
		coords = np.vstack((Kx.flatten(), Ky.flatten())).T
		theta *= 180 / np.pi
		self.data = interp(coords).reshape(Kx.shape)[::-1]
		self.dx = (kr[0, 1] - kr[0, 0]) 
		self.dy = theta[1, 0] - theta[0, 0]
		

		self.x_origin = 0
		return self

	
	def show_overlaped(self, map2, fig = None, axs = None, kw1 = {}, kw2 = {}):
		"""
		shows field, overlapped by map2
		"""
		if axs is None:
			fig, axs = plt.subplots(1, 1)
		if not isinstance(axs, Iterable):
			axs = [axs]
		self.show(fig, axs[[0, 1]] if len(axs) == 3 else axs[0], **kw1)
		map2.show(fig, axs[[0, 2]] if len(axs) == 3 else axs[0], **kw2)



